import { Product, Category, StoreSettings } from './types';

export const initialCategories: Category[] = [
  { id: 1, name: 'خدمات السوشيال ميديا', name_en: 'Social Media Services', slug: 'social-media', icon: 'Share2', sort_order: 1, is_active: 1 },
  { id: 2, name: 'الاشتراكات الرقمية', name_en: 'Digital Subscriptions', slug: 'subscriptions', icon: 'Tv', sort_order: 2, is_active: 1 },
  { id: 3, name: 'مفاتيح التفعيل والبرامج', name_en: 'Software & License Keys', slug: 'software-keys', icon: 'Key', sort_order: 3, is_active: 1 },
  { id: 4, name: 'حسابات الألعاب والترفيه', name_en: 'Gaming & Accounts', slug: 'gaming-accounts', icon: 'Gamepad2', sort_order: 4, is_active: 1 },
  { id: 5, name: 'أدوات التصميم والذكاء الاصطناعي', name_en: 'Design & AI Tools', slug: 'ai-design-tools', icon: 'Wand2', sort_order: 5, is_active: 1 }
];

export const initialProducts: Product[] = [
  {
    id: 1,
    category_id: 1,
    name: 'متابعو انستقرام حقيقيون ومضمونون',
    name_en: 'Instagram Real Followers',
    slug: 'instagram-followers-real',
    description: 'زيادة متابعين انستقرام حسابات حقيقية ونشطة مع ضمان عدم النقص لمدة 30 يوم. تنفيذ سريع وآمن على حسابك بدون الحاجة لكلمة المرور نهائياً.',
    description_en: 'High quality real Instagram followers with 30-day refill guarantee. Safe and quick delivery without requiring your password.',
    type: 'service',
    base_price: 15.00,
    discount_price: 12.00,
    stock: 9999,
    sku: 'IG-FL-01',
    delivery_type: 'manual',
    delivery_time_text: 'يبدأ خلال 15 دقيقة إلى ساعتين',
    is_featured: 1,
    is_active: 1,
    image: 'https://images.unsplash.com/photo-1611262588024-d12430b98920?w=800&auto=format&fit=crop&q=80',
    rating: 4.9,
    total_reviews: 142,
    variants: [
      { id: 101, product_id: 1, title: '1,000 متابع حقيقي', title_en: '1,000 Real Followers', sku: 'IG-1K', price: 15.00, discount_price: 12.00, stock: 9999, delivery_time: '1-3 ساعات', is_active: 1, sort_order: 1 },
      { id: 102, product_id: 1, title: '2,500 متابع حقيقي', title_en: '2,500 Real Followers', sku: 'IG-2.5K', price: 35.00, discount_price: 28.00, stock: 9999, delivery_time: '2-4 ساعات', is_active: 1, sort_order: 2 },
      { id: 103, product_id: 1, title: '5,000 متابع حقيقي', title_en: '5,000 Real Followers', sku: 'IG-5K', price: 65.00, discount_price: 52.00, stock: 9999, delivery_time: '3-6 ساعات', is_active: 1, sort_order: 3 },
      { id: 104, product_id: 1, title: '10,000 متابع VIP', title_en: '10,000 VIP Followers', sku: 'IG-10K', price: 120.00, discount_price: 95.00, stock: 9999, delivery_time: '6-12 ساعة', is_active: 1, sort_order: 4 },
      { id: 105, product_id: 1, title: '25,000 متابع مع هدايا تفاعل', title_en: '25,000 Followers + Bonus', sku: 'IG-25K', price: 280.00, discount_price: 220.00, stock: 9999, delivery_time: '12-24 ساعة', is_active: 1, sort_order: 5 }
    ],
    requirements: [
      { id: 201, product_id: 1, field_label: 'اسم المستخدم في انستقرام (Username)', field_label_en: 'Instagram Username', field_type: 'text', placeholder: '@your_username (بدون كلمة المرور)', is_required: 1, sort_order: 1 },
      { id: 202, product_id: 1, field_label: 'رابط الحساب المباشر', field_label_en: 'Profile URL', field_type: 'url', placeholder: 'https://instagram.com/your_account', is_required: 1, sort_order: 2 },
      { id: 203, product_id: 1, field_label: 'ملاحظات إضافية للتنفيذ', field_label_en: 'Additional Notes', field_type: 'textarea', placeholder: 'أي تعليمات خاصة بالطلب...', is_required: 0, sort_order: 3 }
    ]
  },
  {
    id: 2,
    category_id: 1,
    name: 'تفاعل ولايكات تيك توك نشطة وسريعة',
    name_en: 'TikTok Likes & Fast Engagement',
    slug: 'tiktok-likes-fast',
    description: 'باقات إعجابات تيك توك لزيادة ظهور مقاطعك في صفحة For You (Explore). سرعة عالية في الإرسال وأمان تام على حسابك.',
    description_en: 'TikTok video likes to boost visibility on For You page. Fast and secure delivery.',
    type: 'service',
    base_price: 8.00,
    discount_price: 6.50,
    stock: 9999,
    sku: 'TT-LK-02',
    delivery_type: 'manual',
    delivery_time_text: 'فوري خلال 10-30 دقيقة',
    is_featured: 1,
    is_active: 1,
    image: 'https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800&auto=format&fit=crop&q=80',
    rating: 4.8,
    total_reviews: 98,
    variants: [
      { id: 106, product_id: 2, title: '1,000 لايك تيك توك', title_en: '1,000 TikTok Likes', sku: 'TT-1K', price: 8.00, discount_price: 6.50, stock: 9999, delivery_time: '15 دقيقة', is_active: 1, sort_order: 1 },
      { id: 107, product_id: 2, title: '5,000 لايك تيك توك', title_en: '5,000 TikTok Likes', sku: 'TT-5K', price: 30.00, discount_price: 24.00, stock: 9999, delivery_time: '30 دقيقة', is_active: 1, sort_order: 2 },
      { id: 108, product_id: 2, title: '10,000 لايك تيك توك + شير', title_en: '10,000 Likes + Shares', sku: 'TT-10K', price: 55.00, discount_price: 44.00, stock: 9999, delivery_time: 'ساعة واحدة', is_active: 1, sort_order: 3 }
    ],
    requirements: [
      { id: 204, product_id: 2, field_label: 'رابط فيديو التيك توك المستهدف', field_label_en: 'TikTok Video URL', field_type: 'url', placeholder: 'https://www.tiktok.com/@user/video/...', is_required: 1, sort_order: 1 }
    ]
  },
  {
    id: 3,
    category_id: 2,
    name: 'اشتراك نتفلكس بريميوم 4K رسمي (ملف خاص مقفل برمز)',
    name_en: 'Netflix Premium 4K Official',
    slug: 'netflix-premium-4k',
    description: 'اشتراك رسمي بأعلى جودة Ultra HD 4K، ملف شخصي مستقل خاص بك ومقفل برمز سري PIN، يعمل على الشاشات الذكية، الهواتف، والكمبيوتر، مع ضمان كامل المدة.',
    description_en: 'Official Netflix Premium Ultra HD 4K subscription with private profile and PIN. Works on all devices.',
    type: 'subscription',
    base_price: 35.00,
    discount_price: 29.00,
    stock: 45,
    sku: 'NFLX-4K',
    delivery_type: 'account',
    delivery_time_text: 'تسليم فوري بعد الدفع مباشرة',
    duration_days: 30,
    is_featured: 1,
    is_active: 1,
    image: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=800&auto=format&fit=crop&q=80',
    rating: 5.0,
    total_reviews: 310,
    variants: [
      { id: 109, product_id: 3, title: 'شهر واحد (30 يوم)', title_en: '1 Month (30 Days)', sku: 'NFLX-1M', price: 35.00, discount_price: 29.00, stock: 40, delivery_time: 'فوري', duration_days: 30, is_active: 1, sort_order: 1 },
      { id: 110, product_id: 3, title: '3 أشهر (90 يوم) - الأكثر طلباً', title_en: '3 Months (90 Days)', sku: 'NFLX-3M', price: 95.00, discount_price: 79.00, stock: 25, delivery_time: 'فوري', duration_days: 90, is_active: 1, sort_order: 2 },
      { id: 111, product_id: 3, title: 'سنة كاملة (365 يوم)', title_en: '1 Year (365 Days)', sku: 'NFLX-1Y', price: 350.00, discount_price: 279.00, stock: 10, delivery_time: 'فوري', duration_days: 365, is_active: 1, sort_order: 3 }
    ],
    requirements: []
  },
  {
    id: 4,
    category_id: 2,
    name: 'اشتراك يوتيوب بريميوم رسمي على إيميلك الشخصي',
    name_en: 'YouTube Premium Official',
    slug: 'youtube-premium-official',
    description: 'تفعيل رسمي بدون إعلانات وتنزيل المقاطع وخلفية الشاشة وYouTube Music على حسابك الشخصي عبر دعوة رسمية بدون طلب كلمة مرورك.',
    description_en: 'Official YouTube Premium activation on your own personal Google account without ads.',
    type: 'subscription',
    base_price: 18.00,
    discount_price: 14.00,
    stock: 120,
    sku: 'YT-PRM',
    delivery_type: 'manual',
    delivery_time_text: 'خلال 15-30 دقيقة',
    duration_days: 30,
    is_featured: 1,
    is_active: 1,
    image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop&q=80',
    rating: 4.9,
    total_reviews: 215,
    variants: [
      { id: 112, product_id: 4, title: 'اشتراك 3 أشهر', title_en: '3 Months Subscription', sku: 'YT-3M', price: 25.00, discount_price: 19.00, stock: 80, delivery_time: '15-30 دقيقة', duration_days: 90, is_active: 1, sort_order: 1 },
      { id: 113, product_id: 4, title: 'اشتراك 6 أشهر', title_en: '6 Months Subscription', sku: 'YT-6M', price: 45.00, discount_price: 36.00, stock: 50, delivery_time: '15-30 دقيقة', duration_days: 180, is_active: 1, sort_order: 2 },
      { id: 114, product_id: 4, title: 'اشتراك سنة كاملة (12 شهر)', title_en: '12 Months (Full Year)', sku: 'YT-1Y', price: 80.00, discount_price: 64.00, stock: 40, delivery_time: '15-30 دقيقة', duration_days: 365, is_active: 1, sort_order: 3 }
    ],
    requirements: [
      { id: 205, product_id: 4, field_label: 'إيميل حساب قوقل / يوتيوب الشخصي', field_label_en: 'Your Google Account Email', field_type: 'email', placeholder: 'example@gmail.com', is_required: 1, sort_order: 1 }
    ]
  },
  {
    id: 5,
    category_id: 3,
    name: 'مفتاح تفعيل ويندوز 11 برو أصلي مدى الحياة (Windows 11 Pro)',
    name_en: 'Windows 11 Pro Genuine Lifetime Key',
    slug: 'windows-11-pro-key',
    description: 'مفتاح رقمي أصلي 100% لتفعيل ويندوز 11 برو لجهاز كمبيوتر واحد مدى الحياة مع دعم التحديثات الرسمية من مايكروسوفت.',
    description_en: '100% Genuine digital retail license key for Windows 11 Pro. Lifetime activation on 1 PC with official updates.',
    type: 'digital',
    base_price: 45.00,
    discount_price: 19.99,
    stock: 88,
    sku: 'WIN11-PRO',
    delivery_type: 'code',
    delivery_time_text: 'فوري برسالة SMS وإيميل وفي الموقع',
    is_featured: 1,
    is_active: 1,
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop&q=80',
    rating: 5.0,
    total_reviews: 180,
    variants: [],
    requirements: []
  },
  {
    id: 6,
    category_id: 3,
    name: 'أوفيس 365 برو بلس أصلي (5 أجهزة + 1TB سحابي)',
    name_en: 'Microsoft Office 365 Pro Plus Account',
    slug: 'office-365-pro-plus',
    description: 'حساب رسمي لمايكروسوفت أوفيس 365 يمنحك Word, Excel, PowerPoint, Outlook وغيرها على 5 أجهزة مع مساحة تخزين سحابي OneDrive سعة 1000 جيجابايت.',
    description_en: 'Official Microsoft Office 365 account for 5 devices (PC, Mac, Mobile) with 1TB OneDrive cloud storage.',
    type: 'digital',
    base_price: 55.00,
    discount_price: 29.00,
    stock: 60,
    sku: 'OFFICE-365',
    delivery_type: 'account',
    delivery_time_text: 'فوري تلقائياً',
    is_featured: 1,
    is_active: 1,
    image: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&auto=format&fit=crop&q=80',
    rating: 4.9,
    total_reviews: 140,
    variants: [],
    requirements: []
  },
  {
    id: 7,
    category_id: 5,
    name: 'اشتراك كانفا برو رسمي مدى الحياة (Canva Pro Team Invite)',
    name_en: 'Canva Pro Official Lifetime Access',
    slug: 'canva-pro-lifetime',
    description: 'تفعيل كانفا برو الرسمي بكافة القوالب والخطوط وأدوات الذكاء الاصطناعي ومزيل الخلفيات بنقرة واحدة على إيميلك الشخصي.',
    description_en: 'Official Canva Pro invitation on your own personal email. Full access to premium templates, fonts, and AI magic tools.',
    type: 'subscription',
    base_price: 30.00,
    discount_price: 15.00,
    stock: 150,
    sku: 'CANVA-PRO',
    delivery_type: 'manual',
    delivery_time_text: 'خلال 10-20 دقيقة',
    duration_days: 365,
    is_featured: 1,
    is_active: 1,
    image: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&auto=format&fit=crop&q=80',
    rating: 4.9,
    total_reviews: 420,
    variants: [],
    requirements: [
      { id: 206, product_id: 7, field_label: 'إيميل حسابك في كانفا', field_label_en: 'Your Canva Account Email', field_type: 'email', placeholder: 'your_email@example.com', is_required: 1, sort_order: 1 }
    ]
  },
  {
    id: 8,
    category_id: 5,
    name: 'اشتراك شات جي بي تي بلس (ChatGPT Plus - GPT-4o)',
    name_en: 'ChatGPT Plus (GPT-4o) Official',
    slug: 'chatgpt-plus-official',
    description: 'وصول مباشر لأقوى نماذج الذكاء الاصطناعي GPT-4o وDALL-E 3 وتوليد الصور وتصفح الإنترنت وتحليل الملفات بسرعة فائقة وبدون قيود.',
    description_en: 'Direct access to OpenAI GPT-4o, DALL-E 3 image generation, browsing and advanced data analysis.',
    type: 'subscription',
    base_price: 85.00,
    discount_price: 69.00,
    stock: 25,
    sku: 'GPT-PLUS',
    delivery_type: 'account',
    delivery_time_text: 'خلال 15 دقيقة',
    duration_days: 30,
    is_featured: 1,
    is_active: 1,
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&auto=format&fit=crop&q=80',
    rating: 5.0,
    total_reviews: 195,
    variants: [],
    requirements: []
  }
];
