<?php
/**
 * Digitex Store - Production cPanel Web Installer
 * Runs on Namecheap cPanel via http://yourdomain.com/install
 */

session_start();
$lockFile = __DIR__ . '/installed.lock';

if (file_exists($lockFile)) {
    die('<div style="font-family:sans-serif; text-align:center; padding:50px; direction:rtl;">
        <h2 style="color:#e11d48;">تم تثبيت المتجر مسبقاً</h2>
        <p>نظام التثبيت مغلق لدواعي الأمان. لإعادة التثبيت قم بحذف ملف <code>installed.lock</code> داخل مجلد <code>/install</code>.</p>
        <a href="../" style="display:inline-block; padding:10px 20px; background:#4f46e5; color:#fff; text-decoration:none; border-radius:8px; margin-top:15px;">الذهاب للمتجر</a>
    </div>');
}

$step = isset($_GET['step']) ? intval($_GET['step']) : 1;
$error = null;
$success = null;

// Handle Form Submissions
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $action = $_POST['action'] ?? '';

    if ($action === 'test_db') {
        $host = trim($_POST['db_host']);
        $name = trim($_POST['db_name']);
        $user = trim($_POST['db_user']);
        $pass = $_POST['db_pass'];

        try {
            $pdo = new PDO("mysql:host=$host;dbname=$name;charset=utf8mb4", $user, $pass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
            ]);
            $_SESSION['db_config'] = [
                'host' => $host,
                'name' => $name,
                'user' => $user,
                'pass' => $pass
            ];
            header('Location: index.php?step=3');
            exit;
        } catch (PDOException $e) {
            $error = "تعذر الاتصال بقاعدة البيانات: " . $e->getMessage();
        }
    }

    if ($action === 'complete_install') {
        $dbConfig = $_SESSION['db_config'] ?? null;
        if (!$dbConfig) {
            header('Location: index.php?step=2');
            exit;
        }

        $adminName = trim($_POST['admin_name']);
        $adminEmail = trim($_POST['admin_email']);
        $adminPass = $_POST['admin_password'];
        $storeName = trim($_POST['store_name']);
        $currency = trim($_POST['currency']);

        if (strlen($adminPass) < 6) {
            $error = "كلمة المرور يجب أن لا تقل عن 6 خانات";
        } else {
            try {
                $pdo = new PDO("mysql:host={$dbConfig['host']};dbname={$dbConfig['name']};charset=utf8mb4", $dbConfig['user'], $dbConfig['pass'], [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
                ]);

                // Run schema.sql
                $schemaFile = __DIR__ . '/../../database/schema.sql';
                if (!file_exists($schemaFile)) {
                    $schemaFile = __DIR__ . '/../database/schema.sql';
                }
                
                if (file_exists($schemaFile)) {
                    $sql = file_get_contents($schemaFile);
                    $pdo->exec($sql);
                }

                // Update Admin credentials
                $hashedPass = password_hash($adminPass, PASSWORD_BCRYPT);
                $stmt = $pdo->prepare("UPDATE admins SET name = ?, email = ?, password = ? WHERE id = 1");
                $stmt->execute([$adminName, $adminEmail, $hashedPass]);

                // Update Store name & currency
                $stmt2 = $pdo->prepare("UPDATE settings SET value = ? WHERE `key` = 'store_name'");
                $stmt2->execute([$storeName]);
                $stmt3 = $pdo->prepare("UPDATE settings SET value = ? WHERE `key` = 'default_currency'");
                $stmt3->execute([$currency]);

                // Create .env file
                $envContent = "# Generated by Digitex Installer on " . date('Y-m-d H:i:s') . "\n";
                $envContent .= "DB_HOST={$dbConfig['host']}\n";
                $envContent .= "DB_PORT=3306\n";
                $envContent .= "DB_NAME={$dbConfig['name']}\n";
                $envContent .= "DB_USER={$dbConfig['user']}\n";
                $envContent .= "DB_PASS=\"{$dbConfig['pass']}\"\n";
                $envContent .= "APP_ENV=production\n";
                $envContent .= "APP_DEBUG=false\n";
                $envContent .= "DEFAULT_CURRENCY={$currency}\n";

                file_put_contents(__DIR__ . '/../../.env', $envContent);

                // Lock installer
                file_put_contents($lockFile, "Installed on " . date('c'));

                $_SESSION['installed_admin'] = $adminEmail;
                header('Location: index.php?step=4');
                exit;
            } catch (Exception $e) {
                $error = "حدث خطأ أثناء تثبيت الجداول والبيانات: " . $e->getMessage();
            }
        }
    }
}
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>تثبيت متجر Digitex على cPanel</title>
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700;800&display=swap" rel="stylesheet">
    <style>
        * { box-sizing: border-box; font-family: 'Cairo', sans-serif; }
        body { background: #0f172a; color: #f8fafc; margin: 0; padding: 20px; display: flex; align-items: center; justify-content: center; min-height: 100vh; }
        .card { background: #1e293b; border: 1px solid #334155; border-radius: 16px; padding: 32px; max-width: 580px; width: 100%; box-shadow: 0 25px 50px -12px rgba(0,0,0,0.5); }
        .badge { display: inline-block; padding: 4px 12px; border-radius: 9999px; font-size: 12px; font-weight: bold; background: #4f46e5; color: #fff; margin-bottom: 12px; }
        h1 { margin: 0 0 10px; font-size: 24px; color: #ffffff; }
        p { color: #94a3b8; font-size: 14px; line-height: 1.6; }
        .steps { display: flex; justify-content: space-between; margin: 24px 0; border-bottom: 1px solid #334155; padding-bottom: 16px; }
        .step-item { font-size: 13px; color: #64748b; }
        .step-item.active { color: #38bdf8; font-weight: 700; }
        .form-group { margin-bottom: 16px; }
        label { display: block; margin-bottom: 6px; font-size: 13px; color: #cbd5e1; }
        input, select { width: 100%; padding: 12px; background: #0f172a; border: 1px solid #334155; border-radius: 8px; color: #fff; font-size: 14px; outline: none; }
        input:focus { border-color: #6366f1; }
        button, .btn { display: block; width: 100%; text-align: center; background: #4f46e5; color: #fff; border: none; padding: 14px; border-radius: 8px; font-weight: bold; font-size: 15px; cursor: pointer; text-decoration: none; margin-top: 20px; transition: background 0.2s; }
        button:hover, .btn:hover { background: #4338ca; }
        .alert-error { background: #4c0519; border: 1px solid #f43f5e; color: #fecdd3; padding: 12px; border-radius: 8px; font-size: 13px; margin-bottom: 16px; }
        .check-item { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #334155; font-size: 14px; }
        .check-pass { color: #22c55e; font-weight: bold; }
        .check-fail { color: #ef4444; font-weight: bold; }
    </style>
</head>
<body>
    <div class="card">
        <span class="badge">معالج التثبيت الذكي 🚀</span>
        <h1>تثبيت متجر Digitex الرقمي</h1>
        <p>مرحباً بك! يساعدك هذا المعالج على تهيئة المتجر وربط قاعدة بيانات MySQL في ثوانٍ معدودة.</p>

        <div class="steps">
            <span class="step-item <?= $step === 1 ? 'active' : '' ?>">1. الفحص</span>
            <span class="step-item <?= $step === 2 ? 'active' : '' ?>">2. قاعدة البيانات</span>
            <span class="step-item <?= $step === 3 ? 'active' : '' ?>">3. المتجر والمدير</span>
            <span class="step-item <?= $step === 4 ? 'active' : '' ?>">4. الاكتمال</span>
        </div>

        <?php if ($error): ?>
            <div class="alert-error"><?= htmlspecialchars($error) ?></div>
        <?php endif; ?>

        <?php if ($step === 1): ?>
            <h3>متطلبات استضافة cPanel و PHP:</h3>
            <div class="check-item">
                <span>إصدار PHP (المطلوب 8.1+)</span>
                <span class="<?= version_compare(PHP_VERSION, '8.1.0', '>=') ? 'check-pass' : 'check-fail' ?>"><?= PHP_VERSION ?></span>
            </div>
            <div class="check-item">
                <span>امتداد PDO MySQL</span>
                <span class="<?= extension_loaded('pdo_mysql') ? 'check-pass' : 'check-fail' ?>"><?= extension_loaded('pdo_mysql') ? 'مفعّل ✓' : 'غير متوفر ✗' ?></span>
            </div>
            <div class="check-item">
                <span>امتداد OpenSSL</span>
                <span class="<?= extension_loaded('openssl') ? 'check-pass' : 'check-fail' ?>"><?= extension_loaded('openssl') ? 'مفعّل ✓' : 'غير متوفر ✗' ?></span>
            </div>
            <div class="check-item">
                <span>امتداد MBString</span>
                <span class="<?= extension_loaded('mbstring') ? 'check-pass' : 'check-fail' ?>"><?= extension_loaded('mbstring') ? 'مفعّل ✓' : 'غير متوفر ✗' ?></span>
            </div>
            <div class="check-item">
                <span>صلاحية الكتابة على المجلدات</span>
                <span class="<?= is_writable(__DIR__) ? 'check-pass' : 'check-fail' ?>"><?= is_writable(__DIR__) ? 'متاحة ✓' : 'غير متاحة ✗' ?></span>
            </div>
            <a href="index.php?step=2" class="btn">المتابعة إلى إعداد قاعدة البيانات ←</a>

        <?php elseif ($step === 2): ?>
            <form method="POST">
                <input type="hidden" name="action" value="test_db">
                <div class="form-group">
                    <label>خادم قاعدة البيانات (Host)</label>
                    <input type="text" name="db_host" value="localhost" required>
                </div>
                <div class="form-group">
                    <label>اسم قاعدة البيانات (Database Name)</label>
                    <input type="text" name="db_name" placeholder="مثال: cpaneluser_digitex" required>
                </div>
                <div class="form-group">
                    <label>اسم مستخدم قاعدة البيانات (Database User)</label>
                    <input type="text" name="db_user" placeholder="مثال: cpaneluser_dbuser" required>
                </div>
                <div class="form-group">
                    <label>كلمة مرور قاعدة البيانات (Password)</label>
                    <input type="password" name="db_pass" required>
                </div>
                <button type="submit">اختبار الاتصال والمتابعة ←</button>
            </form>

        <?php elseif ($step === 3): ?>
            <form method="POST">
                <input type="hidden" name="action" value="complete_install">
                <div class="form-group">
                    <label>اسم المتجر (Store Name)</label>
                    <input type="text" name="store_name" value="Digitex Store - متجر الخدمات الرقمية" required>
                </div>
                <div class="form-group">
                    <label>العملة الافتراضية (Default Currency)</label>
                    <select name="currency">
                        <option value="SAR" selected>ريال سعودي (SAR)</option>
                        <option value="JOD">دينار أردني (JOD)</option>
                        <option value="AED">درهم إماراتي (AED)</option>
                        <option value="USD">دولار أمريكي (USD)</option>
                        <option value="KWD">دينار كويتي (KWD)</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>اسم المدير العام (Super Admin Name)</label>
                    <input type="text" name="admin_name" value="مدير المتجر" required>
                </div>
                <div class="form-group">
                    <label>بريد المدير الإلكتروني (Admin Email)</label>
                    <input type="email" name="admin_email" value="admin@yourdomain.com" required>
                </div>
                <div class="form-group">
                    <label>كلمة مرور المدير (Admin Password)</label>
                    <input type="password" name="admin_password" placeholder="أدخل كلمة مرور قوية" required>
                </div>
                <button type="submit">بدء تثبيت الجداول وإنهاء الإعداد 🚀</button>
            </form>

        <?php elseif ($step === 4): ?>
            <div style="text-align:center; padding: 20px 0;">
                <div style="font-size:48px; margin-bottom:12px;">🎉</div>
                <h2 style="color:#22c55e;">مبروك! تم التثبيت بنجاح تام</h2>
                <p>تم استيراد الجداول وتهيئة المتجر وحساب المدير العام وتوليد ملف الإعدادات <code>.env</code> وإغلاق المثبت لحماية المتجر.</p>
                <div style="display:flex; gap:10px; margin-top:24px;">
                    <a href="../" class="btn" style="background:#059669; margin-top:0;">زيارة واجهة المتجر 🛍️</a>
                    <a href="../admin" class="btn" style="background:#4f46e5; margin-top:0;">لوحة تحكم المدير ⚙️</a>
                </div>
            </div>
        <?php endif; ?>
    </div>
</body>
</html>
